# Generated by Django 6.0.7 on 2026-07-15 19:56

import django.core.validators
import profiles.storage
import profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_attachment_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileattachment',
            name='file',
            field=models.FileField(help_text='عکس، صدا، ویدیو یا سند — حداکثر حجم: ۵۰ مگابایت', storage=profiles.storage.get_private_storage, upload_to='profile_attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp3', 'wav', 'ogg', 'm4a', 'aac', 'mp4', 'mov', 'webm', 'avi', 'pdf', 'doc', 'docx']), profiles.validators.MaxFileSizeValidator(50)], verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='audio',
            field=models.FileField(blank=True, help_text='فرمت\u200cهای مجاز: mp3, wav, ogg, m4a, aac — حداکثر حجم: ۲۰ مگابایت', null=True, storage=profiles.storage.get_private_storage, upload_to='session_notes/audio/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg', 'm4a', 'aac']), profiles.validators.MaxFileSizeValidator(20)], verbose_name='فایل صوتی پیوست'),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='image',
            field=models.ImageField(blank=True, help_text='حداکثر حجم: ۱۰ مگابایت', null=True, storage=profiles.storage.get_private_storage, upload_to='session_notes/images/%Y/%m/', validators=[profiles.validators.MaxFileSizeValidator(10)], verbose_name='تصویر پیوست'),
        ),
        migrations.AlterField(
            model_name='sessionnote',
            name='video',
            field=models.FileField(blank=True, help_text='فرمت\u200cهای مجاز: mp4, mov, webm, avi — حداکثر حجم: ۱۰۰ مگابایت', null=True, storage=profiles.storage.get_private_storage, upload_to='session_notes/video/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'webm', 'avi']), profiles.validators.MaxFileSizeValidator(100)], verbose_name='فایل تصویری (ویدیو) پیوست'),
        ),
    ]
