# Generated by Django 6.0.7 on 2026-07-15 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profileattachment_file_alter_sessionnote_audio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileattachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'فایل پیوست پروفایل', 'verbose_name_plural': 'فایل\u200cهای پیوست پروفایل'},
        ),
        migrations.RemoveField(
            model_name='profileattachment',
            name='upload_date',
        ),
    ]
