# Generated by Django 6.0.7 on 2026-07-15 20:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profileattachment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileattachment',
            options={'ordering': ['-upload_date', '-uploaded_at'], 'verbose_name': 'فایل پیوست پروفایل', 'verbose_name_plural': 'فایل\u200cهای پیوست پروفایل'},
        ),
        migrations.AddField(
            model_name='profileattachment',
            name='upload_date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='تاریخی که این فایل به آن تعلق دارد (مثلاً تاریخ جلسه یا تاریخ سند) — به شمسی وارد شود.', verbose_name='تاریخ فایل'),
        ),
    ]
