# Generated by Django 6.0.7 on 2026-07-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profileattachment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionnote',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='sessionnote',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sessionnote',
            name='video',
        ),
    ]
