server {
    listen 80;
    server_name your_domain.com;

    client_max_body_size 110M;

    location /static/ {
        alias /var/www/psychology_site/staticfiles/;
        expires 30d;
    }

    location /media/ {
        alias /var/www/psychology_site/media/;
        expires 30d;
    }

    location / {
        proxy_pass http://unix:/var/www/psychology_site/gunicorn.sock;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
