# Generated by Django 5.0.14 on 2026-07-13 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GAD7Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='امتیاز')),
                ('severity', models.CharField(choices=[('Normal', 'طبیعی'), ('Mild', 'خفیف'), ('Moderate', 'متوسط'), ('Severe', 'شدید')], max_length=20, verbose_name='شدت')),
                ('answers', models.JSONField(verbose_name='پاسخ\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gad7_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نتیجه GAD-7',
                'verbose_name_plural': 'نتایج GAD-7',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PHQ9Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='امتیاز')),
                ('severity', models.CharField(choices=[('Normal', 'طبیعی'), ('Mild', 'خفیف'), ('Moderate', 'متوسط'), ('Moderately Severe', 'نسبتاً شدید'), ('Severe', 'شدید')], max_length=20, verbose_name='شدت')),
                ('answers', models.JSONField(verbose_name='پاسخ\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phq9_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'نتیجه PHQ-9',
                'verbose_name_plural': 'نتایج PHQ-9',
                'ordering': ['-created_at'],
            },
        ),
    ]
