# Generated by Django 6.0.7 on 2026-07-19 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_about_tools_warning'),
        ('core', '0002_alter_sitecontent_id'),
    ]

    operations = [
    ]
